// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// in the admin/ directory to replace this placeholder.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError('Only web platform is supported by this admin app.');
  }

  // TODO: replace all values below after running `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'YOUR_API_KEY',
    appId:             'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId:         'YOUR_PROJECT_ID',
    authDomain:        'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket:     'YOUR_PROJECT_ID.appspot.com',
  );
}
